In [1]:
import seaborn as sns
import metapack as mp
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display 

%matplotlib inline
sns.set_context('notebook')
mp.jupyter.init()

In [2]:
pkg = mp.jupyter.open_package()
#pkg = mp.jupyter.open_source_package()
pkg

# Chronic Absenteeism
`cde.ca.gov-absenteeism-2` Last Update: 2019-05-22T17:42:13

_Student absenteeism data by ethnicity, gender, program subgroup, and grade span. Chronic absenteeism counts, cumulative enrollment, and chronic absenteeism rate data are provided._


## Documentation Links

* [Dataset Homepage](https://www.cde.ca.gov/ds/sd/sd/filesabd.asp)



## Contacts

* **Wrangler** [Eric Busboom](mailto:eric@civicknowledge.com), [Civic Knowledge](http://civicknowledge.com)

## Resources

* ** [chronic_absenteeism](data/chronic_absenteeism.csv)**. Combined Chronic Absenteeism files

## References

* **[chab17](ftp://ftp.cde.ca.gov/demo/attendance/ChrAbsRate1718.txt#target_format=tsv)**. Chronic Absenteeism 2017-2018
* **[chab16](ftp://ftp.cde.ca.gov/demo/attendance/ChrAbsRate1617.txt#target_format=tsv)**. Chronic Absenteeism 2016-2017

In [4]:
df = pkg.resource('chronic_absenteeism').dataframe()
df.head()

,year,academic_year,aggregate_level,county_code,district_code,school_code,county_name,district_name,school_name,is_charter,reporting_category,cumulative_enrollment,chronic_absenteeism_count,cumulative_eligible_enrollment,chronic_absenteeism_rate
0,17,NaN,C,1.0,NaN,NaN,Alameda,NaN,NaN,NaN,GF,114424.0,11448.0,113231.0,10.1
1,17,NaN,C,1.0,NaN,NaN,Alameda,NaN,NaN,NaN,GM,121612.0,12531.0,119966.0,10.4
2,17,NaN,C,1.0,NaN,NaN,Alameda,NaN,NaN,NaN,GR13,53709.0,4402.0,53198.0,8.3
3,17,NaN,C,1.0,NaN,NaN,Alameda,NaN,NaN,NaN,GR46,53798.0,3851.0,53310.0,7.2
4,17,NaN,C,1.0,NaN,NaN,Alameda,NaN,NaN,NaN,GR78,35304.0,2710.0,34987.0,7.7

In [5]:
df.academic_year.value_counts()

Series([], Name: academic_year, dtype: int64)